## Import Data

In [2]:
import pandas as pd
import numpy as np

In [3]:
# use pandas to load data into a DataFrame
df = pd.read_csv("datasets/train.csv")
df.shape # (rows, columns)

(35973, 40)

## Pre-Processing Data

### EDA

In [4]:
df.head()

,id,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,...,DC237f,DC241,DC242,DC244,DC246,DC252,DC270a,DC109,DC142a,DC201
0,1,11,2,16.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,2.0,1,12.0,60.0,Layak Minum
1,2,11,2,31.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,1.0,1.0,2,31.0,70.0,Layak Minum
2,3,11,2,12.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,1.0,1.0,0.0,4,11.0,75.0,Layak Minum
3,6,11,2,12.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,2.0,NaN,1.0,0.0,1.0,1,11.0,85.0,Layak Minum
4,7,11,2,12.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,2,11.0,65.0,Layak Minum

In [5]:
target_column = 'DC201'

In [6]:
df[target_column].replace(to_replace={'Layak Minum':1, 'Tidak Layak Minum':0}, inplace=True)
df.drop('id', axis=1, inplace=True)

In [7]:
df.head()

,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,DC212,...,DC237f,DC241,DC242,DC244,DC246,DC252,DC270a,DC109,DC142a,DC201
0,11,2,16.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,2.0,1,12.0,60.0,1.0
1,11,2,31.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,2,31.0,70.0,1.0
2,11,2,12.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,4,11.0,75.0,1.0
3,11,2,12.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,2.0,NaN,1.0,0.0,1.0,1,11.0,85.0,1.0
4,11,2,12.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,2,11.0,65.0,1.0

In [8]:
df.isna().sum()

DC024         0
DC025         0
DC205        11
DC206        21
DC207        44
DC208        13
DC209        18
DC210        41
DC211        24
DC212        24
DC213        77
DC214         9
DC215        14
DC216        39
DC217         0
DC219         0
DC220         4
DC226         6
DC230a       11
DC230b     3009
DC232      3024
DC232b     3024
DC235     10446
DC237        21
DC237a       37
DC237b       37
DC237c       37
DC237d       37
DC237e       37
DC237f       37
DC241       612
DC242      5374
DC244         4
DC246         9
DC252        14
DC270a        0
DC109        11
DC142a       52
DC201         3
dtype: int64

In [9]:
df = df.fillna(40000)
df = df.astype('int64')
df = df.replace(to_replace={40000:None})
df = df.convert_dtypes()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35973 entries, 0 to 35972
Data columns (total 39 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DC024   35973 non-null  Int64
 1   DC025   35973 non-null  Int64
 2   DC205   35962 non-null  Int64
 3   DC206   35952 non-null  Int64
 4   DC207   35929 non-null  Int64
 5   DC208   35960 non-null  Int64
 6   DC209   35955 non-null  Int64
 7   DC210   35932 non-null  Int64
 8   DC211   35949 non-null  Int64
 9   DC212   35949 non-null  Int64
 10  DC213   35896 non-null  Int64
 11  DC214   35964 non-null  Int64
 12  DC215   35959 non-null  Int64
 13  DC216   35934 non-null  Int64
 14  DC217   35973 non-null  Int64
 15  DC219   35973 non-null  Int64
 16  DC220   35969 non-null  Int64
 17  DC226   35967 non-null  Int64
 18  DC230a  35962 non-null  Int64
 19  DC230b  32964 non-null  Int64
 20  DC232   32949 non-null  Int64
 21  DC232b  32949 non-null  Int64
 22  DC235   25527 non-null  Int64
 23  DC237   35952 non-null  Int64
 24  DC237a  35936 non-null  Int64
 25  DC237b  35936 non-null  Int64
 26  DC237c  35936 non-null  Int64
 27  DC237d  35936 non-null  Int64
 28  DC237e  35936 non-null  Int64
 29  DC237f  35936 non-null  Int64
 30  DC241   35361 non-null  Int64
 31  DC242   30599 non-null  Int64
 32  DC244   35969 non-null  Int64
 33  DC246   35964 non-null  Int64
 34  DC252   35959 non-null  Int64
 35  DC270a  35973 non-null  Int64
 36  DC109   35962 non-null  Int64
 37  DC142a  35921 non-null  Int64
 38  DC201   35970 non-null  Int64
dtypes: Int64(39)
memory usage: 12.0 MB

In [10]:
df_train = df[df['DC201'].notna()]
df_train.isna().sum()

DC024         0
DC025         0
DC205        10
DC206        21
DC207        43
DC208        13
DC209        18
DC210        41
DC211        24
DC212        24
DC213        77
DC214         9
DC215        14
DC216        39
DC217         0
DC219         0
DC220         4
DC226         6
DC230a       11
DC230b     3009
DC232      3024
DC232b     3024
DC235     10444
DC237        19
DC237a       35
DC237b       35
DC237c       35
DC237d       35
DC237e       35
DC237f       35
DC241       612
DC242      5374
DC244         4
DC246         9
DC252        14
DC270a        0
DC109        10
DC142a       52
DC201         0
dtype: int64

### Imputation

In [1]:
big_missing_value = ['DC230b','DC232','DC232b','DC235','DC241','DC242']

In [12]:
df_train = df_train.drop(big_missing_value, axis=1)
df_train

,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,DC212,...,DC237d,DC237e,DC237f,DC244,DC246,DC252,DC270a,DC109,DC142a,DC201
0,11,2,16,1,0,1,0,0,0,0,...,0,0,0,0,0,2,1,12,60,1
1,11,2,31,1,0,1,0,0,1,0,...,0,0,0,1,1,1,2,31,70,1
2,11,2,12,1,0,1,1,1,1,0,...,0,0,0,1,1,0,4,11,75,1
3,11,2,12,1,0,0,0,0,1,0,...,0,0,0,1,0,1,1,11,85,1
4,11,2,12,1,0,1,1,0,0,0,...,1,0,0,0,1,0,2,11,65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35968,94,1,17,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,21,9,1
35969,94,1,12,1,0,1,1,0,0,0,...,0,0,0,0,0,0,2,11,12,1
35970,94,1,12,1,0,1,1,0,1,0,...,0,0,0,0,1,1,1,11,48,1
35971,94,1,12,1,0,1,1,0,1,0,...,0,0,0,0,0,0,2,11,39,1
35972,94,1,12,1,0,1,1,0,1,1,...,0,0,0,0,0,0,3,11,40,1

In [19]:
# import pandas as pd
# from sklearn.impute import KNNImputer

# imputer = KNNImputer(n_neighbors=3)
# knn_x_train = pd.DataFrame(np.round(imputer.fit_transform(df_train)), columns=df_train.columns)

# knn_x_train = knn_x_train.astype('int64')

In [20]:
# knn_x_train['DC109'].unique()

# 12., 31., 11., 41., 32., 21., 51., 33., nan, 96.

array([12, 31, 11, 41, 32, 21, 51, 33, 18, 34, 96, 14])

In [13]:
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer  # noqa
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer
from sklearn.ensemble import ExtraTreesRegressor
#from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import OrdinalEncoder

#instantiate both packages to use
encoder = OrdinalEncoder()
imputer = IterativeImputer(ExtraTreesRegressor())

# create a list of categorical columns to iterate over
cat_cols = list(df_train.columns)
cat_cols.remove('DC142a')
cat_cols.remove('DC220')
cat_cols

['DC024',
 'DC025',
 'DC205',
 'DC206',
 'DC207',
 'DC208',
 'DC209',
 'DC210',
 'DC211',
 'DC212',
 'DC213',
 'DC214',
 'DC215',
 'DC216',
 'DC217',
 'DC219',
 'DC226',
 'DC230a',
 'DC237',
 'DC237a',
 'DC237b',
 'DC237c',
 'DC237d',
 'DC237e',
 'DC237f',
 'DC244',
 'DC246',
 'DC252',
 'DC270a',
 'DC109',
 'DC201']

In [14]:
def encode(data):
    '''function to encode non-null data and replace it in the original data'''
    #retains only non-null values
    nonulls = np.array(data.dropna())
    #reshapes the data for encoding
    impute_reshape = nonulls.reshape(-1,1)
    #encode date
    impute_ordinal = encoder.fit_transform(impute_reshape)
    #Assign back encoded values to non-null values
    data.loc[data.notnull()] = np.squeeze(impute_ordinal)
    return data

#create a for loop to iterate through each column in the data
for columns in cat_cols:
    encode(df_train[columns])

In [15]:
# impute data and convert 
encode_data = pd.DataFrame(np.round(imputer.fit_transform(df_train)),columns = df_train.columns)
encode_data.head()

:

:

### Split Feature and Labels

In [37]:
label = np.array(knn_x_train[target_column]) # value dari label
knn_x_train = knn_x_train.drop(target_column, axis=1) # drop target
feature_list = list(knn_x_train.columns) # list column
feature = np.array(knn_x_train) # df dalam bentuk numpy array

# label = df_train[target_column]
# label = pd.DataFrame(label)
# df_train = df_train.drop(target_column, axis=1)
# feature_list = list(df_train.columns)
# feature = df_train

In [38]:
from collections import Counter
from imblearn.over_sampling import SMOTE

counter = Counter(label)
print(counter)

oversample = SMOTE()
feature, label = oversample.fit_resample(feature, label)

counter = Counter(label)
print(counter)

Counter({1: 32398, 0: 3572})
Counter({1: 32398, 0: 32398})

### Normalization

In [39]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# scaler = MinMaxScaler()
scaler = StandardScaler()
X_train_norm = scaler.fit_transform(feature)
X_train_norm = pd.DataFrame(X_train_norm, columns=feature_list)
X_train_norm

,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,DC212,...,DC237e,DC237f,DC241,DC242,DC244,DC246,DC252,DC270a,DC109,DC142a
0,-1.331116,0.826525,-0.143905,0.365744,-0.359176,0.673722,-0.764669,-0.502791,-1.238653,-0.284694,...,-0.016168,-0.434247,-0.388079,-1.604051,-0.796340,-0.789989,0.814399,-0.858880,-0.564632,-0.165582
1,-1.331116,0.826525,1.765180,0.365744,-0.359176,0.673722,-0.764669,-0.502791,0.807329,-0.284694,...,-0.016168,-0.434247,-0.388079,-1.604051,1.255744,1.265841,-0.100742,-0.117447,0.982096,-0.043690
2,-1.331116,0.826525,-0.652994,0.365744,-0.359176,0.673722,1.307755,1.988898,0.807329,-0.284694,...,-0.016168,-0.434247,-0.388079,-1.604051,1.255744,1.265841,-1.015884,1.365420,-0.646039,0.017255
3,-1.331116,0.826525,-0.652994,0.365744,-0.359176,-1.484293,-0.764669,-0.502791,0.807329,-0.284694,...,-0.016168,-0.434247,1.940897,0.623421,1.255744,-0.789989,-0.100742,-0.858880,-0.646039,0.139147
4,-1.331116,0.826525,-0.652994,0.365744,-0.359176,0.673722,1.307755,-0.502791,-1.238653,-0.284694,...,-0.016168,-0.434247,-0.388079,-1.604051,-0.796340,1.265841,-1.015884,-0.117447,-0.646039,-0.104636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64791,1.223956,0.826525,-0.398450,0.365744,-0.359176,0.673722,-0.764669,-0.502791,-1.238653,-0.284694,...,-0.016168,-0.434247,-0.388079,0.623421,1.255744,1.265841,-1.015884,-0.858880,-0.320412,0.224471
64792,-1.047219,-1.209884,-0.652994,0.365744,-0.359176,0.673722,1.307755,-0.502791,0.807329,-0.284694,...,-0.016168,2.120919,-0.388079,0.623421,-0.796340,-0.789989,-0.100742,1.365420,-0.646039,0.431686
64793,1.548410,0.826525,1.765180,-2.734155,-0.359176,-1.484293,-0.764669,-0.502791,-1.238653,-0.284694,...,-0.016168,-0.434247,-0.388079,0.623421,1.255744,-0.789989,-0.100742,-0.858880,0.982096,0.041634
64794,0.372265,0.826525,-0.652994,0.365744,-0.359176,0.673722,-0.764669,-0.502791,-1.238653,-0.284694,...,-0.016168,-0.434247,1.940897,0.623421,-0.796340,-0.789989,-0.100742,-0.858880,-0.646039,-0.482499
64795,-1.290560,0.826525,1.765180,0.365744,-0.359176,-1.484293,-0.764669,-0.502791,0.807329,-0.284694,...,-0.016168,-0.434247,-0.388079,0.623421,1.255744,-0.789989,-0.100742,-0.858880,0.982096,0.126958

## Modelling

In [40]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split

TEST_SIZE = 0.2
RANDOM_SEED = 42

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_train_norm, label, test_size = TEST_SIZE, random_state = RANDOM_SEED)

In [41]:
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB, BernoulliNB
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report

def model_builder(models, X_train, X_test, y_train, y_test):
    for name, model in models.items():
        model.fit(X_train, y_train)
        predictions = model.predict(X_test)
        print(f"---------------------------- {name} ----------------------------")
        print(classification_report(y_test, predictions, digits=5))

models = {"SVM": SVC(),
          "Logistic Regression": LogisticRegression(),
          "SGD" : SGDClassifier(),
          "Random Forest": RandomForestClassifier(),
          "ADA Boost": AdaBoostClassifier(),
          "Gradient Boosting": GradientBoostingClassifier(),
          "Decision Tree": DecisionTreeClassifier(),
          "KNN" : KNeighborsClassifier(),
          "Gaussian": GaussianNB(),
          "Bernoulli": BernoulliNB(),
          "MLP": MLPClassifier(),
          "XGB": XGBClassifier()}

model_builder(models, X_train, X_test, y_train, y_test)

---------------------------- SVM ----------------------------
              precision    recall  f1-score   support

           0    0.86273   0.89647   0.87928      6520
           1    0.89086   0.85559   0.87287      6440

    accuracy                        0.87616     12960
   macro avg    0.87680   0.87603   0.87607     12960
weighted avg    0.87671   0.87616   0.87609     12960

---------------------------- Logistic Regression ----------------------------
              precision    recall  f1-score   support

           0    0.80931   0.84294   0.82578      6520
           1    0.83401   0.79891   0.81608      6440

    accuracy                        0.82106     12960
   macro avg    0.82166   0.82093   0.82093     12960
weighted avg    0.82158   0.82106   0.82096     12960

---------------------------- SGD ----------------------------
              precision    recall  f1-score   support

           0    0.79149   0.84770   0.81863      6520
           1    0.83386   0.77391   0.80277      6440

    accuracy                        0.81103     12960
   macro avg    0.81268   0.81081   0.81070     12960
weighted avg    0.81255   0.81103   0.81075     12960

---------------------------- Random Forest ----------------------------
              precision    recall  f1-score   support

           0    0.92172   0.94448   0.93296      6520
           1    0.94235   0.91879   0.93042      6440

    accuracy                        0.93171     12960
   macro avg    0.93203   0.93163   0.93169     12960
weighted avg    0.93197   0.93171   0.93170     12960

---------------------------- ADA Boost ----------------------------
              precision    recall  f1-score   support

           0    0.83541   0.86258   0.84878      6520
           1    0.85613   0.82795   0.84181      6440

    accuracy                        0.84537     12960
   macro avg    0.84577   0.84526   0.84529     12960
weighted avg    0.84571   0.84537   0.84531     12960

---------------------------- Gradient Boosting ----------------------------
              precision    recall  f1-score   support

           0    0.85080   0.88160   0.86592      6520
           1    0.87556   0.84348   0.85922      6440

    accuracy                        0.86265     12960
   macro avg    0.86318   0.86254   0.86257     12960
weighted avg    0.86311   0.86265   0.86259     12960

---------------------------- Decision Tree ----------------------------
              precision    recall  f1-score   support

           0    0.86674   0.90675   0.88629      6520
           1    0.90096   0.85885   0.87940      6440

    accuracy                        0.88295     12960
   macro avg    0.88385   0.88280   0.88285     12960
weighted avg    0.88374   0.88295   0.88287     12960

---------------------------- KNN ----------------------------
              precision    recall  f1-score   support

           0    0.82212   0.93926   0.87680      6520
           1    0.92814   0.79425   0.85600      6440

    accuracy                        0.86721     12960
   macro avg    0.87513   0.86676   0.86640     12960
weighted avg    0.87481   0.86721   0.86646     12960

---------------------------- Gaussian ----------------------------
              precision    recall  f1-score   support

           0    0.73313   0.89954   0.80785      6520
           1    0.86794   0.66848   0.75526      6440

    accuracy                        0.78472     12960
   macro avg    0.80053   0.78401   0.78156     12960
weighted avg    0.80012   0.78472   0.78172     12960

---------------------------- Bernoulli ----------------------------
              precision    recall  f1-score   support

           0    0.77736   0.76794   0.77263      6520
           1    0.76791   0.77733   0.77259      6440

    accuracy                        0.77261     12960
   macro avg    0.77264   0.77264   0.77261     12960
weighted avg    0.77267   0.77261   0.77261     12960

/home/danielbudi/miniconda3/envs/tf/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

---------------------------- MLP ----------------------------
              precision    recall  f1-score   support

           0    0.86603   0.90123   0.88328      6520
           1    0.89571   0.85885   0.87689      6440

    accuracy                        0.88017     12960
   macro avg    0.88087   0.88004   0.88008     12960
weighted avg    0.88078   0.88017   0.88010     12960

---------------------------- XGB ----------------------------
              precision    recall  f1-score   support

           0    0.91809   0.92485   0.92145      6520
           1    0.92334   0.91646   0.91989      6440

    accuracy                        0.92068     12960
   macro avg    0.92071   0.92065   0.92067     12960
weighted avg    0.92070   0.92068   0.92068     12960

### Hyperparameter Tuning

In [42]:
# from sklearn.model_selection import GridSearchCV
  
# # defining parameter range
# param_grid = {'C': [0.1, 1, 10, 100, 1000], 
#               'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
#               'kernel': ['rbf','sigmoid','poly','linear']} 

# grid = GridSearchCV(SVC(),
#                     param_grid,
#                     refit = True,
#                     verbose = 3,
#                     cv=5)
  
# # fitting the model for grid search
# grid.fit(X_train, y_train)
# # print best parameter after tuning
# print(grid.best_params_)
  
# # print how our model looks after hyper-parameter tuning
# print(grid.best_estimator_)

In [ ]:
# grid_predictions = grid.predict(X_test)
  
# # print classification report
# print(classification_report(y_test, grid_predictions))

## Cross Validation

In [ ]:
# from numpy import mean
# from numpy import std
# from sklearn.model_selection import cross_val_score
# from sklearn.model_selection import RepeatedStratifiedKFold

In [ ]:
# FOLD = 15
# ITERATIONS = 5

In [ ]:
# param_grid = {'C': [0.009], 
            #   'gamma': [1.2],
            #   'kernel': ['rbf']}

# model = SVC(C=0.009, gamma=1, kernel='rbf')
# cv = RepeatedStratifiedKFold(n_splits=FOLD, n_repeats=ITERATIONS, random_state=RANDOM_SEED)
# n_scores = cross_val_score(model, X_train, y_train, scoring='f1_macro', cv=FOLD, n_jobs=-1, error_score='raise')
# print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

In [ ]:
# print(cross_val_score(model, X_train, y_train, scoring="f1", cv = 5))
# mean_score = cross_val_score(model, X_train, y_train, scoring="f1", cv = 5).mean()
# std_score = cross_val_score(model, X_train, y_train, scoring="f1", cv = 5).std()
# print(mean_score)
# print(std_score)

In [ ]:
# grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3, cv=3)
# grid.fit(X_train, y_train)

In [ ]:
# preds = grid.predict(X_test)

In [ ]:
# print(classification_report(y_test, preds, digits=4))

In [ ]:
# print(classification_report(y_test, preds, digits=4))

In [ ]:
# predictions = pd.DataFrame(preds)
# predictions.to_csv('result.csv', index=False)
# predictions