In [1]:
import numpy as np
import pandas as pd

In [2]:
RANDOM_SEED = 42

In [3]:
# use pandas to load data into a DataFrame
df = pd.read_csv("/kaggle/input/gammafest-water-feasability/mf_df_mapped_smoted.csv")
print(df.shape)
df.head()

(64796, 39)

,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,DC212,...,DC237f,DC241,DC242,DC244,DC246,DC252,DC270a,DC109,DC142a,DC201
0,0,1,1,1,0,1,0,0,0,0,...,0,0,0,0,0,2,0,1,60,1
1,0,1,4,1,0,1,0,0,1,0,...,0,0,0,1,1,1,1,3,70,1
2,0,1,0,1,0,1,1,1,1,0,...,0,0,0,1,1,0,3,0,75,1
3,0,1,0,1,0,0,0,0,1,0,...,0,1,0,1,0,1,0,0,85,1
4,0,1,0,1,0,1,1,0,0,0,...,0,0,0,0,1,0,1,0,65,1

In [4]:
target = 'DC201'

In [6]:
# KUNCI JAWABAN DUNIA

df = df.replace({
    'DC109': {11:0, 12:1, 21:2, 31:3, 32:4, 33:5, 41:6, 51:7, 96:8}, 
    'DC270a': {1:0, 2:1, 3:2, 4:3, 5:4},
    # 'DC252': {2: 20, 1: 10}, same
    # 'DC246': {2: 20, 1: 10},
    # 'DC244': {2: 20, 1: 10},
    # 'DC242': {2: 20, 1: 10},
    'DC241': {1:0, 2:1, 3:2, 6:3},
    'DC237f': {8:2},
    'DC237e': {8:2},
    'DC237d': {8:2},
    'DC237c': {8:2},
    'DC237b': {8:2},
    'DC237a': {8:2},
    'DC237': {8:2},
    'DC235': {1:0, 2:1, 3:2},
    # 'DC232b': {2: 20, 1: 10},
    # 'DC232': {2: 20, 1: 10},
    # 'DC230b': {2: 20, 1: 10},
    'DC230a': {1:0, 2:1, 3:2, 4:3, 5:4},
    'DC226': {1:0, 2:1, 3:2, 4:3, 5:4, 6:5, 7:6, 8:7, 9:8, 10:9, 95:10},
    'DC219': {1:0, 2:1},
    'DC217': {2: 20, 1: 10},
    'DC215': {12:0, 13:1, 21:2, 22:3, 23:4, 31:5, 32:6, 33:7, 34:8, 35:9, 36:10, 96:11},
    'DC214': {12:0, 21:1, 22:2, 23:3, 24:4, 25:5, 26:6, 31:7, 32:8, 34:9, 35:10, 36:11, 37:12, 38:13, 96:14},
    'DC213': {11:0, 21:1, 22:2, 31:3, 32:4, 33:5, 34:6, 35:7, 36:8, 96:9},
    'DC024': {11:0, 12:1, 13:2, 14:3, 15:4, 16:5, 17:6, 18:7, 19:8, 21:9, 31:10, 32:11, 33:12, 34:13, 35:14, 36:15, 51:16,
              52:17, 53:18, 61:19, 62:20, 63:21, 64:22, 65:23, 71:24, 72:25, 73:26, 74:27, 75:28, 76:29, 81:30, 82:31, 91:32, 94:33},
    'DC025': {1:0, 2:1},
    'DC205': {12:0, 16:1, 17:2, 21:3, 31:4, 96:5},
    'DC206': {0:0, 1:1},
    'DC207': {0:0, 1:1},
    'DC208': {0:0, 1:1},
    'DC209': {0:0, 1:1},
    'DC210': {0:0, 1:1},
    'DC211': {0:0, 1:1},
    'DC212': {0:0, 1:1},
    })

In [361]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

NUMERICAL_DATA = ['DC216', 'DC220', 'DC142a']
CATEGORICAL_DATA = [column for column in df.columns if column != target and column not in NUMERICAL_DATA]

numerical_df = df[NUMERICAL_DATA].copy()
categorical_df = df[CATEGORICAL_DATA].astype(str).copy()

norm_numerical_df = scaler.fit_transform(numerical_df)
encoded_df = pd.get_dummies(categorical_df)

merged_df = encoded_df.join(pd.DataFrame(norm_numerical_df))

X = np.array(merged_df)
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,...,169,170,171,172,173,174,175,176,177,178
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.05,0.788235,0.060120
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.10,0.364706,0.070140
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.258824,0.075150
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.15,0.776471,0.085170
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.282353,0.065130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64791,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.05,0.635294,0.150301
64792,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.10,0.388235,0.035070
64793,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.15,0.388235,0.080160
64794,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.400000,0.081162
64795,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.20,0.670588,0.180361

In [392]:
categorical_df.nunique()

DC024     34
DC025      2
DC205      6
DC206      2
DC207      2
DC208      2
DC209      2
DC210      2
DC211      2
DC212      2
DC213     10
DC214     15
DC215     12
DC217      6
DC219      2
DC226     11
DC230a     5
DC230b     2
DC232      2
DC232b     2
DC235      3
DC237      3
DC237a     3
DC237b     3
DC237c     3
DC237d     3
DC237e     3
DC237f     3
DC241      4
DC242      2
DC244      2
DC246      2
DC252      5
DC270a     5
DC109      9
dtype: int64

In [350]:
# from sklearn.preprocessing import MinMaxScaler
# from sklearn.preprocessing import StandardScaler

# # scaler = StandardScaler()
# scaler = MinMaxScaler()

# y = np.array(df[target])
# df_dropped = df.drop(target, axis=1) # drop target
# X = np.array(df_dropped)

# X = scaler.fit_transform(X)
# pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,...,28,29,30,31,32,33,34,35,36,37
0,0.000000,1.0,0.2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.50,0.00,0.125,0.060120
1,0.000000,1.0,0.8,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.000000,0.0,1.0,1.0,0.25,0.25,0.375,0.070140
2,0.000000,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.000000,0.0,1.0,1.0,0.00,0.75,0.000,0.075150
3,0.000000,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.333333,0.0,1.0,0.0,0.25,0.00,0.000,0.085170
4,0.000000,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,1.0,0.00,0.25,0.000,0.065130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64791,0.818182,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,1.00,0.25,0.000,0.150301
64792,0.545455,1.0,0.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,1.0,1.0,1.0,0.50,0.00,0.875,0.035070
64793,0.575758,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.000000,0.0,1.0,1.0,0.25,0.25,0.000,0.080160
64794,0.000000,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.000000,1.0,0.0,0.0,0.25,0.00,0.000,0.081162
64795,0.363636,1.0,0.2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,1.0,0.0,1.0,0.50,0.25,0.375,0.180361

In [362]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, train_size = 0.8,
                                                  random_state = RANDOM_SEED)

# We will keep the shuffle = True since our dataset has not any time dependency.

In [363]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

In [364]:
n = int(len(X_train)*0.8) ## Let's use 80% to train and 20% to eval

In [365]:
X_train_fit, X_train_eval, y_train_fit, y_train_eval = X_train[:n], X_train[n:], y_train[:n], y_train[n:]

In [366]:
xgb = XGBClassifier(tree_method='gpu_hist', gpu_id=0, n_estimators = 1000,
                    learning_rate = 0.1, objective='binary:logistic',
                    random_state = RANDOM_SEED)

# xgb.fit(X_train_fit,y_train_fit, eval_set = [(X_train_eval,y_train_eval)])

In [367]:
from datetime import datetime

def timer(start_time=None):
    if not start_time:
        start_time = datetime.now()
        return start_time
    elif start_time:
        thour, temp_sec = divmod((datetime.now() - start_time).total_seconds(), 3600)
        tmin, tsec = divmod(temp_sec, 60)
        print('\n Time taken: %i hours %i minutes and %s seconds.' % (thour, tmin, round(tsec, 2)))

In [368]:
# create custom loss function
from sklearn.metrics import make_scorer
from sklearn.metrics import classification_report

# custom loss function
def report(y_true, y_pred):
    print(classification_report(y_true, y_pred, digits=4))
    return -1
  
f1 = make_scorer(report, greater_is_better=False)

In [369]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
# from sklearn.model_selection import StratifiedKFold

folds = 5
param_comb = 10

# skf = StratifiedKFold(n_splits=folds, shuffle = True, random_state = RANDOM_SEED)

In [370]:
# random_search = RandomizedSearchCV(xgb, param_distributions=params,
#                                    n_iter=param_comb, scoring='f1_micro', 
#                                    n_jobs=4, cv=skf.split(X_train,y_train), verbose=1, 
#                                    random_state=RANDOM_SEED)

# # Here we go
# start_time = timer(None) # timing starts from this point for "start_time" variable
# random_search.fit(X_train,y_train)
# timer(start_time) # timing ends here for "start_time" variable

In [371]:
# print('\n All results:')
# print(random_search.cv_results_)
# print('\n Best estimator:')
# print(random_search.best_estimator_)
# print('\n Best normalized gini score for %d-fold search with %d parameter combinations:' % (folds, param_comb))
# print(random_search.best_score_ * 2 - 1)
# print('\n Best hyperparameters:')
# print(random_search.best_params_)
# results = pd.DataFrame(random_search.cv_results_)
# results.to_csv('xgb-random-grid-search-results-01.csv', index=False)

In [372]:
# A parameter grid for XGBoost
params = {
        'min_child_weight': [7],
        'gamma': [0.0005],
        'subsample': [0.8],
        'colsample_bytree': [1.0],
        'max_depth': [12]
        }

# {'colsample_bytree': 1.0, 'gamma': 0.3, 'max_depth': 12, 'min_child_weight': 15, 'subsample': 0.8} 0.8666564736217843 94.22% valset
# {'colsample_bytree': 1.0, 'gamma': 0.1, 'max_depth': 12, 'min_child_weight': 15, 'subsample': 0.8} 0.8669266432721585 94.27% valset
# {'colsample_bytree': 1.0, 'gamma': 0.001, 'max_depth': 12, 'min_child_weight': 15, 'subsample': 0.8} 0.8677753975399145 94.31% valset
# {'colsample_bytree': 1.0, 'gamma': 0.0008, 'max_depth': 12, 'min_child_weight': 15, 'subsample': 0.8} 0.8680840692868039 94.31% valset
# {'colsample_bytree': 1.0, 'gamma': 0.0006, 'max_depth': 12, 'min_child_weight': 15, 'subsample': 0.8} 0.8680840692868039 94.27% valset
# {'colsample_bytree': 1.0, 'gamma': 0.0006, 'max_depth': 12, 'min_child_weight': 13, 'subsample': 0.8} 0.8687400079132861 94.25% valset
# {'colsample_bytree': 1.0, 'gamma': 0.0006, 'max_depth': 12, 'min_child_weight': 9, 'subsample': 0.8} 0.8718266211816459 94.54% valset
# {'colsample_bytree': 1.0, 'gamma': 0.0005, 'max_depth': 12, 'min_child_weight': 7, 'subsample': 0.8} 0.8780770863625917 94.68% valset
# {'colsample_bytree': 1.0, 'gamma': 0.0005, 'max_depth': 12, 'min_child_weight': 7, 'subsample': 0.8} 0.8780770863625917
# {'colsample_bytree': 1.0, 'gamma': 0.0005, 'max_depth': 12, 'min_child_weight': 7, 'subsample': 0.8} 0.8789258852877186 no normalization

In [374]:
grid = GridSearchCV(estimator=xgb, param_grid=params,
                    scoring='f1_micro', n_jobs=-1,
                    cv=folds, verbose=3)

start_time = timer(None) # timing starts from this point for "start_time" variable
grid.fit(X_train, y_train)
# grid.fit(X, y)
timer(start_time) # timing ends here for "start_time" variable

Fitting 5 folds for each of 1 candidates, totalling 5 fits

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

 Time taken: 0 hours 0 minutes and 45.55 seconds.

In [375]:
print('\n All results:')
print(grid.cv_results_)
print('\n Best estimator:')
print(grid.best_estimator_)
print('\n Best score:')
print(grid.best_score_ * 2 - 1)
print('\n Best parameters:')
print(grid.best_params_)

 All results:
{'mean_fit_time': array([13.45640898]), 'std_fit_time': array([4.28603391]), 'mean_score_time': array([0.92739544]), 'std_score_time': array([0.09883407]), 'param_colsample_bytree': masked_array(data=[1.0],
             mask=[False],
       fill_value='?',
            dtype=object), 'param_gamma': masked_array(data=[0.0005],
             mask=[False],
       fill_value='?',
            dtype=object), 'param_max_depth': masked_array(data=[12],
             mask=[False],
       fill_value='?',
            dtype=object), 'param_min_child_weight': masked_array(data=[7],
             mask=[False],
       fill_value='?',
            dtype=object), 'param_subsample': masked_array(data=[0.8],
             mask=[False],
       fill_value='?',
            dtype=object), 'params': [{'colsample_bytree': 1.0, 'gamma': 0.0005, 'max_depth': 12, 'min_child_weight': 7, 'subsample': 0.8}], 'split0_test_score': array([0.93229167]), 'split1_test_score': array([0.93315327]), 'split2_test_score': array([0.93025948]), 'split3_test_score': array([0.93556477]), 'split4_test_score': array([0.93315327]), 'mean_test_score': array([0.93288449]), 'std_test_score': array([0.00170708]), 'rank_test_score': array([1], dtype=int32)}

 Best estimator:
XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=1.0, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=0.0005, gpu_id=0, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=12, max_leaves=None,
              min_child_weight=7, missing=nan, monotone_constraints=None,
              n_estimators=1000, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=42, ...)

 Best score:
0.8657689865277642

 Best parameters:
{'colsample_bytree': 1.0, 'gamma': 0.0005, 'max_depth': 12, 'min_child_weight': 7, 'subsample': 0.8}

In [376]:
# print(f"Metrics train:\n\tAccuracy score: {accuracy_score(xgb.predict(X_train),y_train):.4f}\nMetrics test:\n\tAccuracy score: {accuracy_score(xgb.predict(X_val),y_val):.4f}")
# print(f"Metrics train:\n\tAccuracy score: {accuracy_score(random_search.predict(X_train),y_train):.4f}\nMetrics test:\n\tAccuracy score: {accuracy_score(random_search.predict(X_val),y_val):.4f}")
print(f"Metrics train:\n\tAccuracy score: {accuracy_score(grid.predict(X_train),y_train):.4f}\nMetrics test:\n\tAccuracy score: {accuracy_score(grid.predict(X_val),y_val):.4f}")

Metrics train:
	Accuracy score: 0.9996
Metrics test:
	Accuracy score: 0.9411

In [377]:
from sklearn.metrics import classification_report

# predictions = xgb.predict(X_val)
# predictions = random_search.predict(X_val)
predictions = grid.predict(X_val)
print(classification_report(y_val,predictions, digits=4))

              precision    recall  f1-score   support

           0     0.9379    0.9456    0.9417      6520
           1     0.9444    0.9366    0.9405      6440

    accuracy                         0.9411     12960
   macro avg     0.9412    0.9411    0.9411     12960
weighted avg     0.9412    0.9411    0.9411     12960

# Test for submit

In [8]:
test_df = pd.read_csv("/kaggle/input/gammafest-water-feasability/test.csv")
print(test_df.shape)
test_df.head()

(11990, 39)

,id,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,...,DC237e,DC237f,DC241,DC242,DC244,DC246,DC252,DC270a,DC109,DC142a
0,26718,35,2,17,1,0,1,0,1,1,...,0,0,1,1,1,1,1,3,21,52
1,26802,35,1,12,1,1,1,1,0,1,...,0,0,1,1,0,0,1,2,11,18
2,41302,74,2,12,1,0,1,1,1,1,...,0,0,1,0,0,1,4,5,11,78
3,38698,72,1,12,1,1,0,0,0,0,...,0,0,1,0,1,0,0,1,11,20
4,44257,76,2,12,1,0,1,0,0,1,...,0,0,1,1,1,1,1,3,11,125

In [9]:
test_id = test_df.pop('id')

In [10]:
# KUNCI JAWABAN DUNIA

test_df = test_df.replace({
    'DC109': {11:0, 12:1, 21:2, 31:3, 32:4, 33:5, 41:6, 51:7, 96:8}, 
    'DC270a': {1:0, 2:1, 3:2, 4:3, 5:4},
    # 'DC252': {2: 20, 1: 10}, same
    # 'DC246': {2: 20, 1: 10},
    # 'DC244': {2: 20, 1: 10},
    # 'DC242': {2: 20, 1: 10},
    'DC241': {1:0, 2:1, 3:2, 6:3},
    'DC237f': {8:2},
    'DC237e': {8:2},
    'DC237d': {8:2},
    'DC237c': {8:2},
    'DC237b': {8:2},
    'DC237a': {8:2},
    'DC237': {8:2},
    'DC235': {1:0, 2:1, 3:2},
    # 'DC232b': {2: 20, 1: 10},
    # 'DC232': {2: 20, 1: 10},
    # 'DC230b': {2: 20, 1: 10},
    'DC230a': {1:0, 2:1, 3:2, 4:3, 5:4},
    'DC226': {1:0, 2:1, 3:2, 4:3, 5:4, 6:5, 7:6, 8:7, 9:8, 10:9, 95:10},
    'DC219': {1:0, 2:1},
    'DC217': {2: 20, 1: 10},
    'DC215': {12:0, 13:1, 21:2, 22:3, 23:4, 31:5, 32:6, 33:7, 34:8, 35:9, 36:10, 96:11},
    'DC214': {12:0, 21:1, 22:2, 23:3, 24:4, 25:5, 26:6, 31:7, 32:8, 34:9, 35:10, 36:11, 37:12, 38:13, 96:14},
    'DC213': {11:0, 21:1, 22:2, 31:3, 32:4, 33:5, 34:6, 35:7, 36:8, 96:9},
    'DC024': {11:0, 12:1, 13:2, 14:3, 15:4, 16:5, 17:6, 18:7, 19:8, 21:9, 31:10, 32:11, 33:12, 34:13, 35:14, 36:15, 51:16,
              52:17, 53:18, 61:19, 62:20, 63:21, 64:22, 65:23, 71:24, 72:25, 73:26, 74:27, 75:28, 76:29, 81:30, 82:31, 91:32, 94:33},
    'DC025': {1:0, 2:1},
    'DC205': {12:0, 16:1, 17:2, 21:3, 31:4, 96:5},
    'DC206': {0:0, 1:1},
    'DC207': {0:0, 1:1},
    'DC208': {0:0, 1:1},
    'DC209': {0:0, 1:1},
    'DC210': {0:0, 1:1},
    'DC211': {0:0, 1:1},
    'DC212': {0:0, 1:1},
    })

In [11]:
test_df.head()

,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,DC212,...,DC237e,DC237f,DC241,DC242,DC244,DC246,DC252,DC270a,DC109,DC142a
0,14,1,2,1,0,1,0,1,1,0,...,0,0,0,1,1,1,1,2,2,52
1,14,0,0,1,1,1,1,0,1,0,...,0,0,0,1,0,0,1,1,0,18
2,27,1,0,1,0,1,1,1,1,0,...,0,0,0,0,0,1,4,4,0,78
3,25,0,0,1,1,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,20
4,29,1,0,1,0,1,0,0,1,0,...,0,0,0,1,1,1,1,2,0,125

In [14]:
NUMERICAL_DATA = ['DC216', 'DC220', 'DC142a']
CATEGORICAL_DATA = [column for column in test_df.columns if column not in NUMERICAL_DATA]

for i, column in enumerate(CATEGORICAL_DATA):
    print(column, np.sort(test_df.iloc[:,i].unique()))
    print('---')

DC024 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33]
---
DC025 [0 1]
---
DC205 [0 1 2 3 4 5]
---
DC206 [0 1]
---
DC207 [0 1]
---
DC208 [0 1]
---
DC209 [0 1]
---
DC210 [0 1]
---
DC211 [0 1]
---
DC212 [0 1]
---
DC213 [ 0  1  2  3  4  5  6  7  8  9 12]
---
DC214 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
---
DC215 [ 0  1  2  3  4  5  6  7  8  9 10 11]
---
DC217 [ 0  1  2  3  4  5  6  7  8  9 10 18 21 22]
---
DC219 [ 0  3  4  5 10 20]
---
DC226 [0 1]
---
DC230a [13 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37
 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61
 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85
 86 87 88 89 90 91 92 93 94 95]
---
DC230b [0 1 2 3 4 5 6 7 8]
---
DC232 [0 1]
---
DC232b [0 1]
---
DC235 [0 1]
---
DC237 [0 1]
---
DC237a [0 1 2]
---
DC237b [0 1 2]
---
DC237c [0 1 2]
---
DC237d [0 1 2]
---
DC237e [0 1 2]
---
DC237f [0 1 2]
---
DC241 [0 1 2]
---
DC242 [0 1 2]
---
DC244 [0]
---
DC246 [0 1]
---
DC252 [0 1]
---
DC270a [0 1]
---
DC109 [0 1 2 3 4]
---

In [384]:
except_column = ['DC216', 'DC220', 'DC142a']
test_copy = test_df.copy()

for column in test_df.columns:
    if column not in except_column:
        i = 0
        for value in np.sort(test_copy[column].unique()):
            if not np.isnan(value):
                test_copy[column].replace(to_replace={value:i}, inplace=True)
                i += 1

In [389]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

NUMERICAL_DATA = ['DC216', 'DC220', 'DC142a']
CATEGORICAL_DATA = [column for column in test_copy.columns if column != target and column not in NUMERICAL_DATA]

test_num_df = test_copy[NUMERICAL_DATA].copy()
test_cat_df = test_copy[CATEGORICAL_DATA].astype(str).copy()

test_norm_num_df = scaler.fit_transform(test_num_df)
test_encoded_df = pd.get_dummies(test_cat_df)

test_merged_df = test_encoded_df.join(pd.DataFrame(test_norm_num_df))

X = np.array(test_merged_df)
pd.DataFrame(X)

test_cat_df.nunique()

DC024     34
DC025      2
DC205      6
DC206      2
DC207      2
DC208      2
DC209      2
DC210      2
DC211      2
DC212      2
DC213     11
DC214     16
DC215     12
DC217      6
DC219      2
DC226      9
DC230a     2
DC230b     2
DC232      2
DC232b     2
DC235      3
DC237      3
DC237a     3
DC237b     3
DC237c     3
DC237d     3
DC237e     3
DC237f     3
DC241      1
DC242      2
DC244      2
DC246      2
DC252      5
DC270a     5
DC109      9
dtype: int64

In [331]:
# from sklearn.preprocessing import MinMaxScaler
# from sklearn.preprocessing import StandardScaler

# # scaler = StandardScaler()
# scaler = MinMaxScaler()

# # y = np.array(test_copy[target])
# # df_dropped = test_copy.drop(target, axis=1) # drop target
# X = np.array(test_copy)

# X = scaler.fit_transform(X)
# pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,...,28,29,30,31,32,33,34,35,36,37
0,0.424242,1.0,0.4,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,0.25,0.50,0.250,0.052104
1,0.424242,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.25,0.25,0.000,0.018036
2,0.818182,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.00,1.00,0.000,0.078156
3,0.757576,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.000,0.020040
4,0.878788,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,0.25,0.50,0.000,0.125251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11985,0.696970,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.75,0.000,0.070140
11986,0.575758,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.5,0.0,1.0,1.0,0.0,0.00,0.75,0.000,0.120240
11987,0.818182,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.25,0.25,0.000,0.072144
11988,0.818182,1.0,0.8,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.25,0.00,0.875,0.009018
11989,0.909091,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.25,0.25,0.000,0.096192

In [332]:
predictions = grid.best_estimator_.predict(X)
predictions

array([1, 1, 1, ..., 1, 1, 1])

In [333]:
result = []
for prediction in predictions:
    result.append('Layak Minum' if prediction==1 else 'Tidak Layak Minum')
pd.DataFrame(result).value_counts()

Layak Minum          11972
Tidak Layak Minum       18
dtype: int64

In [334]:
finish_pd = pd.DataFrame({'id':test_id.values, 'DC201':result})
finish_pd

          id        DC201
0      26718  Layak Minum
1      26802  Layak Minum
2      41302  Layak Minum
3      38698  Layak Minum
4      44257  Layak Minum
...      ...          ...
11985  36943  Layak Minum
11986  33415  Layak Minum
11987  41998  Layak Minum
11988  41567  Layak Minum
11989  45296  Layak Minum

[11990 rows x 2 columns]

In [282]:
finish_pd.to_csv('result_xgboost_finetuned_minmax_mapped_smote.csv', index=False)

In [283]:
check_pd = pd.read_csv('/kaggle/working/result_xgboost_finetuned_minmax_mapped_smote.csv')
check_pd

          id              DC201
0      26718        Layak Minum
1      26802        Layak Minum
2      41302        Layak Minum
3      38698        Layak Minum
4      44257        Layak Minum
...      ...                ...
11985  36943        Layak Minum
11986  33415        Layak Minum
11987  41998        Layak Minum
11988  41567  Tidak Layak Minum
11989  45296        Layak Minum

[11990 rows x 2 columns]

[CV 2/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.733 total time=  10.0s
[CV 4/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.642 total time=   9.5s
[CV 1/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.938 total time=  14.3s
[CV 3/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.940 total time=  13.6s
[CV 5/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.937 total time=   4.6s
[CV 2/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.733 total time=  13.3s
[CV 4/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.644 total time=  14.8s
[CV 5/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.546 total time=   5.0s
[CV 2/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.733 total time=  13.8s
[CV 4/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.644 total time=  14.2s
[CV 1/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.378 total time=   9.9s
[CV 3/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.796 total time=   9.6s
[CV 5/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.535 total time=   3.3s
[CV 2/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.940 total time=  14.3s
[CV 4/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.942 total time=  13.6s
[CV 1/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.394 total time=  12.9s
[CV 3/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.802 total time=  15.1s
[CV 1/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.394 total time=  13.4s
[CV 3/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.802 total time=  14.3s
[CV 5/5] END colsample_bytree=1.0, gamma=0.0005, max_depth=12, min_child_weight=7, subsample=0.8;, score=0.546 total time=   5.2s